#!/usr/bin/env bash

description "${extension} BDSM extension."

action "install" "Install ${package_name} ${package_version}."
action "uninstall" "Uninstall ${package_name} ${package_version}."

show_help usage
