#!/usr/bin/env bash

description "${extension} BDSM extension."

action "install" "Installs ${package_name} ${package_version}."
action "uninstall" "Uninstalls ${package_name} ${package_version}."

show_help usage
