#!/bin/sh

freetds_initialize()
{
  configure_flags=( --prefix="${install_path}" --with-pic )

  case "${package_version}" in
    (0.9*)
      package define \
        base_url "http://ibiblio.org/pub/Linux/ALPHA/freetds/stable/"
    ;;

    (*)
      package define \
        base_url "http://ibiblio.org/pub/Linux/ALPHA/freetds/old/${package_version}/"
    ;;
  esac
}

# freetds_postfetch()
# {
#   local _directory=$(
#     cd "${source_path}"
#     find . -mindepth 1 -maxdepth 1 -iname "${package_name}-${package_version}*" -type d
#   )
#
#   if variable_is_nonempty _directory
#   then
#     if [[ "${_directory}" != "${package_dir}" ]]
#     then
#       move_directory "${_directory}" to "${package_dir}"
#     fi
#   fi
# }
