#!/bin/sh

openssl_preconfigure()
{
  typeset -gx configure_command

  if os is darwin && os arch type is x86_64
  then configure_command="./Configure darwin64-x86_64-cc"
  else configure_command="./config"
  fi

  __sm.package.configure.flag "--prefix" "${install_path}"

  if (( ${static_flag:-0} == 0 ))
  then configure_flags+=( shared )
  fi

  configure_command+="${configure_flags[@]}"
}
