#!/bin/sh

openssl_preconfigure()
{
  typeset -gx configure_command

  if os is darwin && os arch type is x86_64
  then configure_command="./Configure darwin64-x86_64-cc ${LDFLAGS/-arch x86_64/}"
  else configure_command="./config $LDFLAGS"
  fi

  if (( ${static_flag:-0} == 0 ))
  then __sm.package.configure.flags shared
  fi
}

openssl_postinstall()
{
  if
    (( ${static_flag:-0} == 1 ))
  then
    # This looks like openssl bug - it requires -lz when linking static
    # but it is not available in the default ... not sure what to do with it
    typeset __pc_file="${install_path}/lib/pkgconfig/openssl.pc"
    __sm.files.contain 'Libs:.*-lz' "${__pc_file}" ||
    {
      sed -e '/^Libs:/ s/Libs:/Libs: -lz/' < "${__pc_file}" > "${__pc_file}.replaced" &&
      mv "${__pc_file}.replaced" "${__pc_file}" ||
      {
        typeset __result=$?
        rm -f "${__pc_file}.replaced"
        return ${__result}
      }
    }
  fi
}
