#!/usr/bin/env bash

# package_definition \
#   name=ghostscript-fonts-std
#   version=8.11
#   base_url="http://voxel.dl.sourceforge.net/project/gs-fonts/gs-fonts/8.11%20%28base%2035%2C%20GPL%29"
#
# install_code=mv fonts /usr/local/share/ghostscript


package_definition \
  base_url "http://voxel.dl.sourceforge.net/project/ghostscript/GPL%20Ghostscript/${package_version}"

