#!/bin/sh

libyaml_prefetch()
{
  package define \
    file "yaml-${package_version}.${archive_format}" \
    dir "yaml-${package_version}"
}

libyaml_preconfigure()
{
  os is darwin || autoreconf -is --force
}
