#!/bin/sh

librsync_initialize()
{
  package define \
    base_url "http://prdownloads.sourceforge.net/project/librsync/librsync/${package_version}"

  configure_flags+=( --disable-debug --disable-dependency-tracking )
}

